version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bin/dev
    depends_on:
      - database
      - redis
    links:
      - "database"
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: development
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pw'
      MYSQL_ROOT_PASSWORD: 'pw'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /etc/redis/database:/root/redis
    environment:
      - REDIS_PORT=6379

volumes:
  gem_cache:
  node_modules: